---
title: "Creating Patient Symptom Table"
date: "Created: 2019-01-31 <br> Updated: `r Sys.Date()`"
output: 
  html_notebook:
    toc: true
    toc_float: true
    css: custom-css.css
---

# Overview

Creating patient symptom table.... Jared can fill in


# Load packages and data

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
Sys.setenv(TZ = "US/Central")
```

```{r message=FALSE}
library(tidyverse)
library(bfuncs)
```

```{r}
symptoms <- feather::read_feather("/Volumes/SPH/Research/Detect/one_year_data/symptoms.feather")
```

```{r}
about_data(symptoms) # 28,228 observations and 2 variables
```

[top](#top)










# Find all symptoms

* Figure out how to break character stings into component symptoms   
* Get list of all unique symptoms   
* Turn symptoms into binary variables   
* Create new table of symptoms   
* Create two-way table of symptoms by incident complaint   

```{r}
new <- stringr::str_replace_all("''Nausea (R11.0)'',''Vomiting, unspecified (R11.10)'',''Weakness (R53.1)'',''Other malaise (R53.81)''", "'", "") 
```

```{r}
stringr::str_split(
  "''Nausea (R11.0)'',''Vomiting, unspecified (R11.10)'',''Weakness (R53.1)'',''Other malaise (R53.81)''", 
  "(?<=\\))'',''"
) 
```

```{r}
unique(symptoms$symptoms) %>% 
  stringr::str_split("(?<=\\))'',''") %>% 
  unlist() %>% 
  unique() %>% 
  stringr::str_remove_all("'")
```


[top](#top)










# Session information

```{r echo=FALSE}
rm(list = ls())
```

```{r echo=FALSE}
sessionInfo()
```